#!/usr/bin/env lua

---
--- Expense Tracker CLI
---
local csv_file = "expenses.csv"

local function file_exists(path)
    local file = io.open(path,"r")
    if file then
        file:close()
        return true
    else
        return false
    end
end

local function save_to_csv(expense)
   
    if not file_exists(csv_file) then
        local file = io.open(csv_file, "w") or error("Error: Unable to create file " .. csv_file)

        file:write("id,date,description,amount\n")
        file:close()
    end

    local last_id = 0
    local file = io.open(csv_file, "r") or error("Error: Unable to open file " .. csv_file)

    for line in file:lines() do
        if not line:match("^id,") then
            local id = line:match("^(%d+),")
            if id then
                last_id = math.max(last_id, tonumber(id))
            end
        end
    end
    file:close()
    local next_id = last_id + 1

    local file = io.open(csv_file, "a") or error("Error: Unable to open file " .. csv_file)
    local line = string.format(
        "%d,%s,%s,%.2f\n",
        next_id,
        expense.date,
        expense.description,
        expense.amount
    )
    file:write(line)
    file:close()
    print("expense added successfully (ID: " .. next_id .. ")")
end

local function split_csv(line)
    local t = {}
    for field in string.gmatch(line, "([^,]+)") do
        table.insert(t, field)
    end
    return t
end

local function parse_args(start_index)
    local options = {}
    local i = start_index
    while i <= #arg do
        local current = arg[i]
        if string.sub(current, 1, 2) == "--" then
            local key = string.sub(current, 3)
            local value = arg[i + 1]
            if not value or string.sub(value, 1, 2) == "--" then
                print("Error: Option missing value for " .. current)
                os.exit(1)
            end

            options[key] = value
            i = i + 2
        else
            print("Error: Unexpected argument " .. current)
            i = i + 1
            os.exit(1)
        end
    end
    return options
end

local function add()
    local options = parse_args(2)
    if not options.amount or not options.description then
        print("Error: Missing required options --amount and --description")
        os.exit(1)
    end
    local amount = tonumber(options.amount) * 100
    if not amount then
        print("Error: Invalid amount value")
        os.exit(1)
    end
    local description = options.description
    local date = options.date or os.date("%Y-%m-%d")
    local expense = {
        amount = amount,
        description = description,
        date = date
    }
    save_to_csv(expense)
end

local function list()
    if not file_exists(csv_file) then
        print("No expenses recorded yet.")
        return
    end

    local file = io.open(csv_file, "r") or error("Error: Unable to open file " .. csv_file)

    print("\n📊  EXPENSE LIST")
    print("----------------------------------------------------")
    print(string.format("%-6s | %-12s | %-14s | %-10s","ID", "Date", "Description", "Amount"))
    print("----------------------------------------------------")

    local first_line = true
    for line in file:lines() do
        if first_line then
            first_line = false
            goto continue
        end

        local data = split_csv(line)
        if #data == 4  then
            print(string.format(
            "%-6s | %-12s | %-14s | $ %8.2f",
            data[1],
            data[2],
            data[3],
            data[4]/100
        ))
        end
        ::continue::
    end

    print("----------------------------------------------------")
    file:close()
end


local commands = {
    add = function() add() end,
    list = function() list() end,
    delete = function() print("Delete command not implemented yet") end,
    summary = function() print("Summary command not implemented yet") end
}
local command = arg[1]
if commands[command] then
    commands[command]()
else
    print("Unknown command: " .. command)
    print("Available commands: add, list, delete")
    os.exit(1)
end
